### ISSUE TITLE
Need a testing system

### ISSUE THREAD

**Issue by baskinburak** [USC-ACTLab/splx#1]
We need a proper unit testing.

We can go for [googletest](https://github.com/google/googletest), or [catch2](https://github.com/catchorg/Catch2), or completely something else.

We need to decide on a framework, come up with a testing logic. (i.e. where to put test files, how to run tests together, how to group tests etc.)

**Comment by acevikel** [comment]
Related pointers to this about Google Tests =>

**1-)From googletest readme.md**
https://github.com/google/googletest/blob/master/googletest/README.md#incorporating-into-an-existing-cmake-project

**2-) Example gtest project**
https://github.com/snikulov/google-test-examples

Pointers about catch2 =>

**1-) Google test vs catch2**
TL:DR catch2 is easier to implement and better if the project is not too big (about 70 tests for his case) BUT it doesn't provide breakpoints for tests.  
https://snorristurluson.github.io/Catch2/

**2-) Another happy switch from gtest to catch**
https://anteru.net/blog/2017/from-google-test-to-catch/index.html

My current conclusion:
catch2 will be easier to implement and more understandable

I am updating this as I find new things, just saving to not to lose them

**Comment by baskinburak** [comment]
I found SECTION syntax of catch2 very understandable as well. You need fixtures in googletest for the same effect. But then, you may need to jump back and forth between the fixture and the test case a lot.

Lets go for catch2 then.

**Comment by baskinburak** [comment]
#4 #3 solved.
